---
- name: Install nginx package
  apt:
    pkg:
      - nginx
    state: latest

- name: Set up default nginx site
  copy:
    src: files/nginx-ubuntu.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
